@startuml Trabajo Practico Alquiler de Autos

class Sistema {
    - vehiculos: Vehiculo[]
    - clientes: Cliente[]
    - reservas: Reserva[]

    + ingresarCliente()
    + ingresarVehiculo()
    + ingresarReserva()
 
}

class Vehiculo{
        - nombre
        - Matricula: number
        - estado
        - categoria: CategoriaVehiculo
        - disponibilidad
        - kilometraje

        + getters_y_Setters()
}

abstract class CategoriaVehiculo{
    abstract calcularTarifa()
}
class Compacto extends CategoriaVehiculo{}
class Sedan extends CategoriaVehiculo{}
class SUV extends CategoriaVehiculo{}

class Cliente {
    - nombre
    - dni 

    + hacerReserva()
}

class Reserva{
    - cliente
    - vehiculo 
    - fechaInicio
    - fechaFin

    + actualizarEstadoAuto()
}

@enduml