@startuml Trabajo Practico Alquiler de Autos

    abstract class Vehiculo{
        - nombre
        - Matricula: number
        - estado
        - categoria: CategoriaVehiculo
        - disponibilidad
        - kilometraje

        + getters_y_Setters()
    }

    abstract class CategoriaVehiculo extends Vehiculo{
    }

    class Compacto extends CategoriaVehiculo{}
    class Sedan extends CategoriaVehiculo{}
    class SUV extends CategoriaVehiculo{}

    class Reserva{
        - cliente
        - fechaInicio
        - fechaFin
        + ReservaVehiculo()
    }

    class Tarifa{
        - monto
        + getters_y_Setters()
        + obtenerValor()
    }
    class CalculadoraDeTarifas{
            + calcularTarifa(vehiculo: Vehiculo)
    }

@enduml